# file: roles/entropy/tasks/main.yaml
---

- name: HArdware Volatile Entropy Gathering and Expansion
  with_items:
  - haveged 
  become: yes
  yum: name="{{ item }}"

- name: Enable the entropy service
  become: yes
  service: name=haveged enabled=yes state=started
