# file: roles/entropy/tasks/main.yaml
---

- name: HArdware Volatile Entropy Gathering and Expansion
  become: yes
  yum:
    name: "haveged"

- name: Enable the entropy service
  become: yes
  service:
    name: haveged
    enabled: yes
    state: started
