# file: roles/dynect_session/handlers/main.yaml
---

- name: End DynECT API session
  local_action:
    module: uri
    method: DELETE 
    url: "{{ dynect_api_url }}/Session/"
    headers:
      Content-Type: "application/json"
      Auth-Token: "{{ dynect_session_token }}"
  changed_when: False
