# file: roles/dynect_session/tasks/main.yaml
#
# Starts a DynECT DNS management API session.
#
---

- name: Establish a DynECT API session
  no_log: True
  local_action:
    module: uri
    method: POST
    url: "{{ dynect_api_url }}/Session/"
    headers:
      Content-Type: "application/json"
    body_format: json
    body:
      customer_name: "{{ dynect_customer }}"
      user_name: "{{ dynect_api_user }}"
      password: "{{ dynect_api_password }}"
    return_content: yes
  register: dynect_session_result
  changed_when: True
  notify: End DynECT API session

- name: Set the DynECT API session as a fact
  when: dynect_session_result is success and
        "success" == dynect_session_result.json.status
  no_log: True
  set_fact:
    dynect_session_token: "{{ dynect_session_result.json.data.token }}"
